[package]
name = "wgpu_struct_derive"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Macros for wgpu_struct"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = "2.0.111"
